# image: ghcci/x86_64-linux:0.0.4

before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  #- git config --global user.email "user@example.com"
  #- git config --global user.name "User name"
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - sudo apt-get update -y
  - sudo apt-get install jq wget -y
  - 'which ssh-agent || sudo apt-get install openssh-client -y'
  - eval $(ssh-agent -s)
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

# All validation jobs keep the bindists and test results are artifacts,
# when we get far enough to generate them.
#
# This requires updating the maximum artifacts size limit in Gitlab to
# something like 200MB.

validate-x86_64-linux:
  script: ".gitlab/circle-ci-job.sh validate-x86_64-linux"
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - ghc.tar.xz
      - junit.xml

validate-i386-linux:
  script: ".gitlab/circle-ci-job.sh validate-i386-linux"
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - ghc.tar.xz
      - junit.xml

# validate-x86_64-freebsd:
#   script: ".gitlab/circle-ci-job.sh validate-x86_64-freebsd"
#   artifacts:
#     when: always
#     reports:
#       junit: junit.xml
#     paths:
#       - ghc.tar.xz
#       - junit.xml

validate-x86_64-darwin:
  script: ".gitlab/circle-ci-job.sh validate-x86_64-darwin"
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - ghc.tar.xz
      - junit.xml

validate-hadrian-x86_64-linux:
  script: ".gitlab/circle-ci-job.sh validate-hadrian-x86_64-linux"
  # the testsuite doesn't pass with hadrian yet...
  #
  # artifacts:
  #   when: always
  #   reports:
  #     junit: junit.xml
  #   paths:
  #     - ghc.tar.xz
  #     - junit.xml

# validate-x86_64-linux-unreg:
#   script: ".gitlab/circle-ci-job.sh validate-x86_64-linux-unreg"
#   artifacts:
#     when: always
#     reports:
#       junit: junit.xml
#     paths:
#       - ghc.tar.xz
#       - junit.xml

# validate-x86_64-linux-llvm:
#   script: ".gitlab/circle-ci-job.sh validate-x86_64-linux-llvm"
#   artifacts:
#     when: always
#     reports:
#       junit: junit.xml
#     paths:
#       - ghc.tar.xz
#       - junit.xml

# validate-x86_64-linux-debug:
#   script: ".gitlab/circle-ci-job.sh validate-x86_64-linux-debug"
#   artifacts:
#     when: always
#     reports:
#       junit: junit.xml
#     paths:
#       - ghc.tar.xz
#       - junit.xml

# slow-validate-x86_64-linux:
#   script: ".gitlab/circle-ci-job.sh slow-validate-x86_64-linux"
#   artifacts:
#     when: always
#     reports:
#       junit: junit.xml
#     paths:
#       - ghc.tar.xz
#       - junit.xml
